name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:            
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Overwrite env variables
        run: |
          echo "env_variables:" >> app.yaml
          echo "  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}" >> app.yaml
          echo "  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}" >> app.yaml
          
      - name: echo
        run: cat app.yaml
      
      - name: Build
        run: |
          yarn
          yarn build

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GAE_PROJECT }}
          service_account_key: ${{ secrets.GAE_KEY_FILE}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy
